### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by RikkaW** [RikkaApps/Shizuku#9]
- [x] use different dex for different API version
- [ ] try `ServiceManager.addService` for root mode
- [ ] add all APIs
